spring:
  profiles:
    active: prd

logging:
  #  level:
  #    root: info
  #    com.learn.log.LoggerTest: error #������·���»��·������־����
  #    com.learn.log.LombokTest: info
  #  file: D:/java/SpringBootLearn/001-spring-boot-log/log/logback.log
  #config: src/main/resources/logback-spring-${spring.profiles.active}.xml
  config: src/main/resources/logback-spring.xml


